name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user vscode
      env:
        CODESPACES: true
    steps:
      - run: sudo chmod -R a+rwX ${RUNNER_TEMP} ${RUNNER_WORKSPACE}
      - uses: actions/checkout@v3
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: test nix-installed commands
        run: |
          source "${HOME}/.zshenv"
          source "${HOME}/.zshrc"
          command ls "${HOME}/.nix-profile"
          command ls "${HOME}/.nix-profile/bin"
          command ls "${HOME}/.nix-profile/etc"
          command ls "${HOME}/.nix-profile/etc/profile.d"
          env | sort
          fzf --version
          tldr --version
          tldr gh
        shell: zsh {0}