name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user vscode
      env:
        CODESPACES: true
    steps:
      - run: sudo chmod -R a+rwX ${RUNNER_TEMP} ${RUNNER_WORKSPACE}
      - uses: actions/checkout@v3
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: install zsh
        run: sudo apt-get install --no-install-recommends -y zsh
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: test nix-installed commands
        run: |
          fzf --version
          tldr --version
          tldr gh
        shell: zsh +f {0}