name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user vscode
      env:
        CODESPACES: true
    steps:
      - run: env | sort
      - run: sudo chown -R vscode:vscode ${RUNNER_TEMP} ${RUNNER_WORKSPACE}
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
