name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user vscode
      env:
        CODESPACES: true
        USER: vscode
    steps:
      - uses: actions/checkout@v3
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: test nix-installed commands
        run: |
          fzf --version
          tldr --version
          tldr gh
        shell: zsh {0}
